### ISSUE TITLE
ResClasses breaks GAP  \< methods

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/resclasses#3]
As @fingolfin pointed out in https://github.com/gap-system/gap/issues/2164, ResClasses provides

```gap
InstallMethod( \<, "for a list of elements and a ring (ResClasses)",
               IsIdenticalObj, [ IsList, IsRing ], 0, ReturnFalse );
...
InstallMethod( \<, "for a ring and a list of elements (ResClasses)",
               IsIdenticalObj, [ IsRing, IsList ], 0, ReturnTrue );
```
and therefore we have
```
gap> GF(3) < [0*Z(3)]; # without resclasses
false
gap> GF(3) < [0*Z(3)]; # with resclasses
true
```
and thus it changes the behaviour for standard objects defined in the core GAP system. This is not allowed.

**Comment by olexandr-konovalov** [comment]
Another example:
```
gap> GF(3) < AsList(GF(3)); # without resclasses
false
gap> GF(3) < AsList(GF(3)); # with resclasses
true
```

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl can we modify method filters to apply only to specific objects defined in RCWA, or to have some extra check and `TryNextMethod` for non-RCWA cases?

**Comment by Stefan-Kohl** [comment]
@alex-konovalov What you can do easily is to do a TryNextMethod for all rings for which ResClasses does not provide functionality (i.e. for all rings except for Z, Z_pi and GF(q)[x] for some prime power q), and for all lists which do not only contain elements of the particular ring in question. Everything else probably needs more careful thought.
